### ISSUE TITLE
Form label, hint text, error message and input filed spacing

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#211]
Incorrect spacing after the hint text. Please match current GEL spacing for all.

<img width="1500" alt="Form spacing" src="https://github.com/WestpacGEL/GEL-next/assets/936597/fdce960c-1325-4038-86b7-4b2496ccff01">

**Comment by samithaf** [comment]
@justinspencer current GEL is using `line-height: 1.428571429`; and `font-size: 0.875rem` as the base but there is no design token associated with that combination. 

But in the new code we were using `typography-10` token as the base which leads to this difference since typography-10 `line-height:1.4`. 

Can I propose to create a new design token `typography-11` with `line-height: 1.428571429`; and `font-size: 0.875rem`?

cc. @KateMacdonald @tomjackking

**Comment by samithaf** [comment]
fixed. cc @justinspencer
