### ISSUE TITLE
Spacing tokens

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#241]
There seems to be odd number spacing tokens and I'm wondering why? 3px is useful for spacing very small elements however beyond 6px I've always used multiples of 6.

<img width="1210" alt="Too many spacing tokens" src="https://github.com/WestpacGEL/GEL-next/assets/936597/a0588eca-472a-4157-a659-844c916c4e79">

**Comment by samithaf** [comment]
Hello @justinspencer, It is because GEL is using multiplications of 3. 

Here are few places. 

- 9px - Button component - xLarge size - padding top
- 15px - Button component - large size - padding left and padding right

Also [we documented all the places](https://github.com/WestpacGEL/GEL-next/discussions/234) we had to hardcode values to match with current GEL and could not use tokens.

**Comment by justinspencer** [comment]
Hi @samithaf. I think there may be some confusion around the concept of Spacing tokens. From a design perspective Spacing tokens should be used to space elements/components on a screen. We use these to ensure a consistent scale and rhythm in the design. We don't need tokens to add padding to elements like buttons and accordion items as these are intended to have very specific heights.

**Comment by samithaf** [comment]
@justinspencer also note that, this is not something we added new and current production GEL also got all those space token values, https://westpacgel.netlify.app/core/tokens-spacing

**Comment by justinspencer** [comment]
Fair enough. I hadn't noticed that.
