### ISSUE TITLE
Date picker disappearing close button

### ISSUE THREAD

**Issue by justinspencer** [WestpacGEL/GEL-next#259]
There's something odd happening with the close button when opening the calendar in desktop (Safari). The close button is visible and has focus then it vanishes and the focus moves to the date. This also happens in the current GEL version. Not sure what's supposed to happen but I'm guessing it's not this. See video attached.

https://github.com/WestpacGEL/GEL-next/assets/936597/58cb5e51-11c6-4df6-966d-4e91b79f605c

**Comment by samithaf** [comment]
@jaortiz @KateMacdonald can you reproduce this issue? for some reason I can't replicate in my macOS Safari

**Comment by jaortiz** [comment]
@justinspencer I've looked into this is and it seems to be an issue with the duet datepicker library we are using. I've looked into their source code and found a way to maybe fix it but since we don't own it we cant change it and the library seems to be unmaintained since the last change update was a couple years ago. We also think this issue is to do with older laptops graphics cards rendering as we've tested on newer laptops and can't recreate the issue.
