### ISSUE TITLE
Separate the components (have one component per page)

### ISSUE THREAD

**Issue by kenjishiromajp** [WestpacGEL/GEL-next#650]

**Comment by KateMacdonald** [comment]
@kenjishiromajp @samithaf I think this issue is about the new Input/Select/Text area pages? I just noticed that the code pages still have examples that show all input types. It doesn't bother me, but thought I would point it out.
![image](https://github.com/WestpacGEL/GEL-next/assets/6667337/6907f5bc-f685-4838-94ef-df9896b600ab)
